### ISSUE TITLE
segfault on url click

### ISSUE THREAD

**Issue by tomamplius** [rhysd/Mstdn#1]
Log : 
Application launched!
Send config to renderer procress
Opened URL with external browser (new-window) https://github.com/rhysd/Mstdn
Erreur de segmentation (core dumped)

**Comment by rhysd** [comment]
You are using Windows, right?

Electron seems to have a bug. https://github.com/electron/electron/issues/9230

I added a workaround for this in v0.1.2. Could you try the latest?

**Comment by tomamplius** [comment]
Linux Ubuntu 16.04 with the zip archive v0.1.2

**Comment by rhysd** [comment]
I see. I'll check it on VM

**Comment by tomamplius** [comment]
same with open-mstdn-app after npm install -g mstdn 
I use xubuntu, sorry

**Comment by rhysd** [comment]
I could reproduce this with Ubuntu 16.04.

**Comment by algernon** [comment]
Seeing something similar here too (Ubuntu 16.10), running from master.

**Comment by rhysd** [comment]
Yeah, it may be crossplatform bug of Electron or Chromium. I'll update the Electron issue.

**Comment by rhysd** [comment]
I need to add the same workaround as Windows for Linux. It would be included in next release.

**Comment by tomamplius** [comment]
Fix in 0.1.3 Merci

**Comment by rhysd** [comment]
Thank you for confirming that quickly :smile:
