### ISSUE TITLE
Taskbar at top of desktop breaks window size

### ISSUE THREAD

**Issue by rhysd** [rhysd/Mstdn#10]
This issue was reported in mstdn.jp.

https://mstdn.jp/@vsngrv2/2043492

I guess electron-window-state fails to obtain correct coordinate of window. I need to check this issue on Windows with the precondition.

**Comment by osapon** [comment]
I am also. My environment is

* Windows 10 Pro (x64)
* The task bar is on the left of the screen
* Resolution 4K, Scale is 150%

Window size is
  1598 x 1862
  1628 x 1952
  1658 x 2042
  1688 x 2124
And it will become bigger.

**Comment by rhysd** [comment]
Thank you for sharing your information. You're using `"normal_window": true`, right? (actually it's a default value. So if you didn't change the config, it would be.)

**Comment by osapon** [comment]
Yes. config.json is `"normal_window": true`

**Comment by rhysd** [comment]
I confirmed this bug on Windows 8.1 with setting taskbar at top of desktop.

**Comment by rhysd** [comment]
I'll close this issue because it was addressed in v0.2.2. Please try the latest. If you find there is still a bug, please let me know by commenting this thread or making a new issue.
