### ISSUE TITLE
Display problems in Kubuntu 16.04 64bit

### ISSUE THREAD

**Issue by TwistedLucidity** [rhysd/Mstdn#13]
On initial launch, all I got was a white windows (no title, border or menu).

After going into "config.json" and setting _"normal_window": true_, it gained the border, title and menu; but that was all. Where I expected to see the my account was just white. I don't get to see a login prompt or anything.

I don't think I missed a set-up step, but I guess it is possible.

I installed from the 0.2.2 from the Linux 64bit .zip here https://github.com/rhysd/Mstdn/releases

![blank](https://cloud.githubusercontent.com/assets/4239996/25288562/d59ffec8-26bd-11e7-855c-01c0f5d285b0.png)

**Comment by rhysd** [comment]
Thank you for reporting that. Could you try to run app with debug mode?

```
$ NODE_ENV=development /path/to/Mstdn
```

It will output debug logs to stdout, and it also launch DevTools when renderer process starts. Please see what happens.

**Comment by TwistedLucidity** [comment]
Thanks for that, turns out it was PEBKAC (i.e. me being stupid) and the dev tools made it obvious.
I had missed this section in the instructions "https:// is not necessary."

**Comment by rhysd** [comment]
Oh, I see. I just added the instruction today. So, it looks my fault. Thank you for clarifying that anyway :+1:
