### ISSUE TITLE
Drag window

### ISSUE THREAD

**Issue by edsu** [rhysd/Mstdn#15]
I feel kind of silly for asking this question, but has anyone else had problems with dragging the Mstdn app window around on the desktop? It launches in the middle of the screen and I can resize it but I can't seem to move it.

I'm on OS X / 10.12 and using the latest Mstdn that's on master 506055084a3fea925dd70152344f31de29f83f3e

![screen shot 2017-04-24 at 8 13 49 am](https://cloud.githubusercontent.com/assets/33829/25336539/fccd01a8-28c5-11e7-8f5f-a877af901184.png)

**Comment by rhysd** [comment]
I think you (or someone) should set below.

```json
{
  ...

  "normal_window": true,

  ...
}
```

There are two window modes in Mstdn app.

- **menubar mode**: Window is attached to menubar,  you can toggle window by clicking icon in menubar or typing hot key. Advantage of this mode is you can check the timeline with small window anytime, without filling a workspace by window.
- **normal window mode**: Window is opened as a normal application window. This works as a separated normal browser window with some desktop features like notifications.

In macOS or Linux, menubar mode is enabled by default. If you want to move a window like normal browser window, you should use normal window mode.

I think I need to describe more about this in README.md.

**Comment by edsu** [comment]
Yes, that did it thanks! It seems like `true` would be a sensible default?

**Comment by rhysd** [comment]
I feel which mode should be default is a matter of style of usage of this app. So I can't say which is sensible default. (On Windows, normal window is default because menubar mode does not work well)

**Comment by edsu** [comment]
I think it's interesting that it's called `normal_window` since the word normal kind of implies that it's the default. Although now that I know about the hot-key it makes a lot more sense.

**Comment by rhysd** [comment]
um, the option may be confusing as you said. I should have make `"menubar": true/false` option (`"menubar": true` corresponds to `"normal_window": false`).

**Comment by edsu** [comment]
Perhaps this is a cultural difference of some kind? I'm just not so familiar with the idea of menubar applications. I wasn't suggesting you change the name of the option. I was just pointing out that your choice of words seemed to imply that menubar was not the default behavior :-)

You are doing amazing work, thank you!
