### ISSUE TITLE
Default hotkey is same as default "save as" action...

### ISSUE THREAD

**Issue by JigmeDatse** [rhysd/Mstdn#17]
I am running Mstdn on OS X El Capitan 10.11.6 and it really works well.  This issue is about what the config.json defaults to for the hotkey.  It is ctrlorcmd-shift-s which I think mostly interferes with "save as" in most applications on most operating systems.  

Would it be better to use a "blank" value, or try to find one which isn't really used for much else (at least not across pretty much any application using default keybindings).

**Comment by rhysd** [comment]
Thank you for reporting this.

yeah... actually the `CmdOrCtrl+Shift+S` default config came from my personal settings... I changed it to `CmdOrCtrl+Shift+Enter`. I believe it's more sensible than previous.

As you say, empty value may be even better. But in the case user must set any key sequence to config reading [Electron's accelerator document](https://github.com/electron/electron/blob/master/docs/api/accelerator.md). So I want to see the new default value works well in each OS or not. If it still causes some problem, I'd set default value to empty.

**Comment by JigmeDatse** [comment]
I appreciate this.  I dropped it myself, but felt it was important to "fix".
