### ISSUE TITLE
Keymaps do not work in Windows 10

### ISSUE THREAD

**Issue by jgbresson** [rhysd/Mstdn#18]
I'm on Windows 10 and version 0.2.3

Scroll down, scroll up, and scroll top work for me. However, scroll bottom just scrolls down a little bit, though I'm not exactly sure on the intended behavior here. None of the tab navigation shortcuts work for me.

**Comment by rhysd** [comment]
Didn't you see 'Please do not forget to write your OS and version of Mstdn.app' in the form?

**Comment by jgbresson** [comment]
My bad, I edited the post,

**Comment by rhysd** [comment]
Thank you.

Hmm... There was a problem with CSP on version 0.2.2. Could you tell me which instance you're using? I want to reproduce.

**Comment by jgbresson** [comment]
I'm on mastodon.bigdinosaur.org

Also, none of them seem to be working for me anymore.

**Comment by rhysd** [comment]
I could reproduce it. I think setting `chromium_sandbox` to `false` in `config.json` would solve this issue. Currently Electron has a problem with native sandbox and content security policy. The way to solve this is disabling sandbox. 

https://github.com/electron/electron/issues/9276

**Comment by jgbresson** [comment]
That appeared to do the trick.

 How far down is the scroll bottom shortcut supposed to move the window? For me it just seems to go to one set distance a short way down.

**Comment by jgbresson** [comment]
Fixed in v0.2.4
