### ISSUE TITLE
v0.2.4 on Windows not opening

### ISSUE THREAD

**Issue by jgbresson** [rhysd/Mstdn#20]
Can't get v0.2.4 to open on Windows 10, tried both `Mstdn-win32-ia32-0.2.4.zip` and `Mstdn-win32-x64-0.2.4.zip`.

**Comment by osapon** [comment]
I had no problem with Mstdn-win32-x64-0.2.4.zip. What if you try clearing your browser's cache?

**Comment by jgbresson** [comment]
That didn't work. I've also tried deleting all related files and ding a fresh install, but that didn't work either,

**Comment by rhysd** [comment]
Could you please try to start app with setting environment variable `NODE_ENV`? Please paste the terminal output.

https://github.com/rhysd/Mstdn#how-to-debug

@osapon Thank you for quick comment.

**Comment by rhysd** [comment]
And did 0.2.3 work? 0.2.4 uses the latest beta version Electron. So there may be a bug

**Comment by jgbresson** [comment]
0.2.3 was working for me so that would make sense.

**Comment by rhysd** [comment]
At least in my environment app looks working. So please attach debug log.

https://github.com/rhysd/Mstdn#how-to-debug

**Comment by rhysd** [comment]
Note: If you don't want to make your account public, please hide your account information in log.

**Comment by rhysd** [comment]
I found my mistake on packaging v0.2.4 archives. I updated the release page. If you installed app from release page, could you please download and install the latest again?

https://github.com/rhysd/Mstdn/releases/tag/v0.2.4

**Comment by jgbresson** [comment]
That fixed the problem for me. Thanks for the quick response! It also appears to have fixed the hotkey bug, so I will update that issue accordingly.

**Comment by rhysd** [comment]
@jgbresson Thank you for your confirming that :smile:
