### ISSUE TITLE
A context menu would be incredibly useful

### ISSUE THREAD

**Issue by algernon** [rhysd/Mstdn#21]
By default, Electron provides no context menu on right-clicking. Yet, it would be incredibly useful in Mstdn, if I could right click on a link, and copy the URL, instead of having to click on it, wait for it to open in a browser, and copy the URL.

The [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) package can be of great help in this. I tried to prepare a patch, but my TypeScript knowledge is far too weak for it, it seems.

**Comment by rhysd** [comment]
Thank you for your suggestion. I'll try the package.
