### ISSUE TITLE
I messed up, rip

### ISSUE THREAD

**Issue by zutora** [rhysd/Mstdn#31]
- Your OS: 
- App version: 

Note:
- If you're reporting a bug, please describe how to reproduce it.
- If you're suggesting a new feature, please detailed spec of it.

I was putting in my account info and didn't click the README first. so I didn't know I was supposed to put anything in default_page. and I exited out and of course the app didn't work after that, so I tried deleting and redownloading to reset it, but the file I edited is deep down in my computer and I cannot find it. Please help, I currently do not have Mstdn zip file or application folder on my computer right now.

**Comment by zutora** [comment]
you gonna fucking help me?

**Comment by HorlogeSkynet** [comment]
You should watch your language before anything else
