### ISSUE TITLE
Cannot invoke open-mstdn-app after Yarn installation

### ISSUE THREAD

**Issue by lofidevops** [rhysd/Mstdn#32]
- Your OS: Ubuntu 17.04
- App version: Latest (via Yarn)

**Steps to reproduce:**

* [Install Yarn on Ubuntu](https://yarnpkg.com/en/docs/install)
* Install mstdn with `yarn global add mstdn --prefix /usr/local` (failed)
* Install mstdn with `sudo yarn global add mstdn --prefix /usr/local` (worked)
* Invoke `open-mstdn-app`

**What should happen:**

* mstdn starts

**What happens instead:**

* `open-mstdn-app: command not found`

**Notes:**

* I found `open-mstdn-app` in `~/.config/yarn/global/node_modules/.bin` but if I invoke `./open-mstdn-app` from there I get: `/usr/bin/env: ‘node’: No such file or directory`
* Are you considering other packaging options (deb, flatpak, snappy)?

**Comment by rhysd** [comment]
Why don't you use npm?

**Comment by rhysd** [comment]
I'm not using yarn. So I'm not sure that this is a problem of this package or your usage of yarn.

**Comment by lofidevops** [comment]
This was resolved by:
* Installing the `nodejs-legacy` package (creates a symlink from `node` to `nodejs`)
* Re-running `sudo yarn global add mstdn --prefix /usr/local`
* Invoking `open-mstdn-app`

**Comment by rhysd** [comment]
I see. Thank you for your investigation. It's actually a problem with old `nodejs` package in some Linux distributions, I think.
