### ISSUE TITLE
Cannot close application

### ISSUE THREAD

**Issue by ostaszewskik** [rhysd/Mstdn#44]
- Your OS: Ubuntu 16.04
- App version: v0.2.6

I don't see any option to close the application, I shut it down using gnome-sytem-monitor / pkill option. Is there any more "polite" way to do it?

**Comment by Tina-otoge** [comment]
I believe it's Ctrl+Q,

I had to enable "normal_window" mode to see it. The menu bar at the top has a Quit option and the keybing "Ctrl+Q" is associated with it, that's how I found it.
