### ISSUE TITLE
Can not login to SINGLE_USER_MODE enabled instances.

### ISSUE THREAD

**Issue by ernix** [rhysd/Mstdn#5]
Some instances use `SINGLE_USER_MODE` option that redirects the top page to user profile page.
It would be nice if it opens up '/auth/sign_in' path directly.

![screen shot 2017-04-20 at 19 27 21](https://cloud.githubusercontent.com/assets/343556/25226485/148aebe8-2600-11e7-9b4b-ec326732f702.png)

**Comment by rhysd** [comment]
Thank you for reporting this! I actually didn't know the single user mode. I'll try to change a page shown before login.

**Comment by rhysd** [comment]
This issue should be addressed in 9c3f0fe. Please wait for next release.

**Comment by rhysd** [comment]
I'll close this issue because it was addressed in v0.2.2. Please try the latest. If you find there is still a bug, please let me know by commenting this thread or making a new issue.
