### ISSUE TITLE
No menu on Linux, even with hide_menu set to false

### ISSUE THREAD

**Issue by jjatria** [rhysd/Mstdn#6]
Having no menus, it is impossible to access multiple accounts, etc. And when navigating to the "about" page of an instance, there is actually no way to go back at all.

This is running on Kubuntu 16.10.

The `hide_menu` key in config is set to the default value of `false`.

![no_border](https://cloud.githubusercontent.com/assets/2975989/25231084/56751628-25ce-11e7-8d9d-8ab82fa29f76.png)

**Comment by rhysd** [comment]
I haven't used Kubuntu so please let me ask questions.

1. In Kubuntu, where is a menu shown in general?
2. Is the screenshot a normal window on you desktop? (It looks to lose window frame...)

And please note that you can use key shortcuts to navigate pages or switching accounts.

**Comment by rhysd** [comment]
`"normal_window": true` option may help you.

**Comment by jjatria** [comment]
Yup, that fixed it. Thanks!

**Comment by rhysd** [comment]
You're welcome!
