### ISSUE TITLE
Window disappears on losing focus on Linux

### ISSUE THREAD

**Issue by jjatria** [rhysd/Mstdn#7]
When the application loses focus, the window disappears entirely. In order to show it again, it needs to be selected from the system tray icon. And when it does appear, it does so flush against the top right corner of the screen, regardless of where it had been before.

This is on Kubuntu 16.10.

**Comment by larryni** [comment]
Same issue here on Mint 17.3 (Mate).

**Comment by jjatria** [comment]
Maybe we're thinking about this the wrong way, and the issue is related to monochrome profile pictures... :thinking:

**Comment by rhysd** [comment]
Window is dismissed when it loses a focus by default. You can display the window again by clicking icon in tray or by typing hot key (please see `hot_key` config in `config.json`).

If you want a window to remain in desktop after losing its focus, please try `"always_on_top": true` config option or `"normal_window": true`.

**Comment by larryni** [comment]
Thanks, the normal_window option does what I wanted it to do. It also remembers the position when I move it to my secondary screen.

**Comment by jjatria** [comment]
Thanks! Setting `normal_window` to `true` solves the issue for me.

**Comment by rhysd** [comment]
You're welcome!
